//! Probe-matrix generator — tier 5 (procedures & OO).
//!
//! Reads a curated manifest of probe specs from `manifest.rs` and
//! emits, into the workspace:
//!
//!   - One `.cp` source per probe at `Mod/Tests/Matrix/<Name>.cp`.
//!   - A single `tests/newcp-tests/src/matrix_generated.rs` declaring
//!     one `#[test]` per probe, each calling `run_function` and
//!     asserting the expected packed result.
//!
//! See `docs/test_matrix.md` for the wider testing strategy this
//! sits inside.  The manifest is hand-curated, not Cartesian — we
//! seed it with the cells the recent bug class taught us matter
//! (pointer-alias receivers, value-mode params, plain-record
//! dispatch) and grow it as new feature interactions surface.
//!
//! Re-running this binary is the only supported way to update the
//! generated files.  Hand edits to `matrix_generated.rs` or to
//! `Mod/Tests/Matrix/*.cp` will be clobbered on the next run.

mod manifest;

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use manifest::{Probe, MANIFEST};

fn main() -> std::io::Result<()> {
    // Resolve the workspace root by walking up from `CARGO_MANIFEST_DIR`
    // until we find the top-level `Cargo.toml` whose [workspace] block
    // lists our crate.  Two `..` jumps does it: src/newcp-test-matrix → .
    let crate_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo"));
    let workspace_root = crate_dir
        .parent()
        .and_then(Path::parent)
        .expect("workspace layout: <root>/src/newcp-test-matrix")
        .to_path_buf();

    let probes_dir = workspace_root.join("Mod").join("Tests").join("Matrix");
    fs::create_dir_all(&probes_dir)?;

    // The generated file lives inside `mod tests` (defined inline in
    // lib.rs).  Inline-module submodule resolution looks under
    // `src/tests/`, so emit there.
    let tests_subdir = workspace_root
        .join("tests")
        .join("newcp-tests")
        .join("src")
        .join("tests");
    fs::create_dir_all(&tests_subdir)?;
    let test_file = tests_subdir.join("matrix_generated.rs");

    // Emit one .cp per probe.
    for probe in MANIFEST {
        let cp_path = probes_dir.join(format!("{}.cp", probe.module_name));
        fs::write(&cp_path, probe.cp_source)?;
        println!(
            "wrote {} (CP §{}, expect {})",
            cp_path.display(),
            probe.spec_section,
            probe.expected_value,
        );
    }

    // Emit the single matrix_generated.rs test file.
    let test_source = render_test_file(MANIFEST);
    fs::write(&test_file, test_source)?;
    println!("wrote {} ({} probes)", test_file.display(), MANIFEST.len());

    Ok(())
}

fn render_test_file(probes: &[Probe]) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by newcp-test-matrix-gen — do not edit by hand.\n");
    out.push_str("// Re-run `cargo run -p newcp-test-matrix` to regenerate.\n");
    out.push_str("//\n");
    out.push_str("// Each probe is one cell of the tier-5 (procedures & OO) test\n");
    out.push_str("// matrix described in `docs/test_matrix.md`.  Spec-§ tags let\n");
    out.push_str("// a future coverage report group cells by language-report rule.\n");
    out.push_str("\n");
    out.push_str("#![allow(non_snake_case)]\n");
    out.push_str("\n");
    // This file is declared as `mod matrix_generated;` inside the
    // inline `mod tests { ... }` block of `lib.rs`, so `super`
    // resolves to that test module and `run_function` is its
    // sibling helper.
    out.push_str("use super::run_function;\n");
    out.push_str("\n");

    for probe in probes {
        out.push_str(&format!(
            "/// CP §{} — {}\n",
            probe.spec_section, probe.description
        ));
        out.push_str("#[test]\n");
        if let Some(reason) = probe.ignored {
            // Multi-line ignore reasons get joined into one Rust
            // string literal so `cargo test -- --list` can render
            // them.  Quote-escape any embedded backslashes / quotes
            // defensively, though the manifest stays prose-only.
            let escaped = reason.replace('\\', "\\\\").replace('"', "\\\"");
            out.push_str(&format!("#[ignore = \"{escaped}\"]\n"));
        }
        out.push_str(&format!("fn matrix_{}() {{\n", probe.test_name));
        out.push_str("    assert_eq!(\n");
        out.push_str(&format!(
            "        run_function(\"Mod/Tests/Matrix/{}.cp\", \"Run\"),\n",
            probe.module_name
        ));
        // The probe description lands inside a Rust format string —
        // escape literal `{` / `}` (e.g. SET literals like `{0..7}`)
        // so the macro doesn't treat them as placeholders.
        let desc_escaped = probe
            .description
            .replace('{', "{{")
            .replace('}', "}}")
            .replace('"', "\\\"");
        out.push_str(&format!(
            "        {},\n        \"matrix probe {} ({} \u{2014} §{}) returned the wrong value\",\n",
            probe.expected_value, probe.test_name, desc_escaped, probe.spec_section
        ));
        out.push_str("    );\n");
        out.push_str("}\n\n");
    }

    out
}
