// GENERATED by newcp-test-matrix-gen — do not edit by hand.
// Re-run `cargo run -p newcp-test-matrix` to regenerate.
//
// Each probe is one cell of the tier-5 (procedures & OO) test
// matrix described in `docs/test_matrix.md`.  Spec-§ tags let
// a future coverage report group cells by language-report rule.

#![allow(non_snake_case)]

use super::run_function;

/// CP §10.2 — pointer-alias receiver overrides an ABSTRACT method on the base (regression: pointer-alias receiver binding)
#[test]
fn matrix_recv_ptr_alias_new_on_abstract() {
    assert_eq!(
        run_function("Mod/Tests/Matrix/M_RecvPtrAlias_NewOnAbstract.cp", "Run"),
        770,
        "matrix probe recv_ptr_alias_new_on_abstract (pointer-alias receiver overrides an ABSTRACT method on the base (regression: pointer-alias receiver binding) — §10.2) returned the wrong value",
    );
}

/// CP §10.2 / 6.4 — NEW method on a plain (non-extensible) record — must emit a direct call, not a vtable dispatch (regression: plain-record dispatch)
#[test]
fn matrix_recv_value_style_new_on_plain() {
    assert_eq!(
        run_function("Mod/Tests/Matrix/M_RecvValueStyle_NewOnPlain.cp", "Run"),
        4242,
        "matrix probe recv_value_style_new_on_plain (NEW method on a plain (non-extensible) record — must emit a direct call, not a vtable dispatch (regression: plain-record dispatch) — §10.2 / 6.4) returned the wrong value",
    );
}

/// CP §10.1 / 8.1 — value-mode record param — callee mutation must NOT leak (regression: pass-by-value semantics for records)
#[test]
fn matrix_param_value_record_is_private_copy() {
    assert_eq!(
        run_function("Mod/Tests/Matrix/M_Param_Value_Record.cp", "Run"),
        42,
        "matrix probe param_value_record_is_private_copy (value-mode record param — callee mutation must NOT leak (regression: pass-by-value semantics for records) — §10.1 / 8.1) returned the wrong value",
    );
}

/// CP §10.1 / 8.1 — value-mode fixed-array param — callee mutation must NOT leak (regression: pass-by-value for arrays)
#[test]
fn matrix_param_value_fixed_array_is_private_copy() {
    assert_eq!(
        run_function("Mod/Tests/Matrix/M_Param_Value_FixedArray.cp", "Run"),
        7,
        "matrix probe param_value_fixed_array_is_private_copy (value-mode fixed-array param — callee mutation must NOT leak (regression: pass-by-value for arrays) — §10.1 / 8.1) returned the wrong value",
    );
}

/// CP §10.1 / 8.1 — value-mode open-array param — callee mutation must NOT leak (regression: prologue memmove on the data buffer)
#[test]
fn matrix_param_value_open_array_is_private_copy() {
    assert_eq!(
        run_function("Mod/Tests/Matrix/M_Param_Value_OpenArray.cp", "Run"),
        7,
        "matrix probe param_value_open_array_is_private_copy (value-mode open-array param — callee mutation must NOT leak (regression: prologue memmove on the data buffer) — §10.1 / 8.1) returned the wrong value",
    );
}

/// CP §10.1 — VAR record param — callee mutation MUST be visible to the caller
#[test]
fn matrix_param_var_record_aliases_caller() {
    assert_eq!(
        run_function("Mod/Tests/Matrix/M_Param_VAR_Record.cp", "Run"),
        999,
        "matrix probe param_var_record_aliases_caller (VAR record param — callee mutation MUST be visible to the caller — §10.1) returned the wrong value",
    );
}

/// CP §10.1 — OUT record param — callee write must materialise in the caller's slot
#[test]
fn matrix_param_out_record_writes_through() {
    assert_eq!(
        run_function("Mod/Tests/Matrix/M_Param_OUT_Record.cp", "Run"),
        7,
        "matrix probe param_out_record_writes_through (OUT record param — callee write must materialise in the caller's slot — §10.1) returned the wrong value",
    );
}

/// CP §10.1 / 8.2 — IN open-array param — LEN(p) inside callee returns the caller's length (regression: hidden $len companion ABI)
#[test]
fn matrix_param_in_open_array_length_visible_via_LEN() {
    assert_eq!(
        run_function("Mod/Tests/Matrix/M_Param_IN_OpenArray_LengthSurvives.cp", "Run"),
        12,
        "matrix probe param_in_open_array_length_visible_via_LEN (IN open-array param — LEN(p) inside callee returns the caller's length (regression: hidden $len companion ABI) — §10.1 / 8.2) returned the wrong value",
    );
}

/// CP §10 / 10.1 — nested proc taking a value-mode open-array; the call site must push the hidden $len companion (regression: nested-call ABI)
#[test]
fn matrix_nested_proc_calls_with_open_array_arg() {
    assert_eq!(
        run_function("Mod/Tests/Matrix/M_Nested_OpenArrayUpvalue.cp", "Run"),
        42,
        "matrix probe nested_proc_calls_with_open_array_arg (nested proc taking a value-mode open-array; the call site must push the hidden $len companion (regression: nested-call ABI) — §10 / 10.1) returned the wrong value",
    );
}

/// CP §10.1 — VAR fixed-array param — callee mutation propagates to the caller
#[test]
fn matrix_param_var_fixed_array_aliases_caller() {
    assert_eq!(
        run_function("Mod/Tests/Matrix/M_Param_VAR_FixedArray.cp", "Run"),
        999,
        "matrix probe param_var_fixed_array_aliases_caller (VAR fixed-array param — callee mutation propagates to the caller — §10.1) returned the wrong value",
    );
}

/// CP §10.1 — VAR open-array param — callee mutation propagates to the caller
#[test]
fn matrix_param_var_open_array_aliases_caller() {
    assert_eq!(
        run_function("Mod/Tests/Matrix/M_Param_VAR_OpenArray.cp", "Run"),
        999,
        "matrix probe param_var_open_array_aliases_caller (VAR open-array param — callee mutation propagates to the caller — §10.1) returned the wrong value",
    );
}

/// CP §10.1 — IN record param — fields readable (write would be a sema error, covered separately by the negative-test corpus)
#[test]
fn matrix_param_in_record_field_readable() {
    assert_eq!(
        run_function("Mod/Tests/Matrix/M_Param_IN_Record.cp", "Run"),
        77,
        "matrix probe param_in_record_field_readable (IN record param — fields readable (write would be a sema error, covered separately by the negative-test corpus) — §10.1) returned the wrong value",
    );
}

/// CP §10.2 / 8.4 — method invoked through a record-field designator (obj.fld.Method()) — receiver lowering must descend through the field GEP
#[test]
#[ignore = "KNOWN BUG: NEW(record_field_pointer) trips IR codegen with `Instr::New: unknown record type opaque:new-ptr`. The IR layer can't resolve the destination's record type when the NEW target is a record field's pointer (vs. a plain local pointer). Surfaced by the matrix on first run — file under deferred_fixes and un-ignore once IR `lower_new` learns to chase the field type."]
fn matrix_method_call_on_record_field_dispatches() {
    assert_eq!(
        run_function("Mod/Tests/Matrix/M_Method_On_RecordField.cp", "Run"),
        21,
        "matrix probe method_call_on_record_field_dispatches (method invoked through a record-field designator (obj.fld.Method()) — receiver lowering must descend through the field GEP — §10.2 / 8.4) returned the wrong value",
    );
}

/// CP §6.5 / 10 — procedure-typed variable invoked via name() syntax — indirect call through the function-pointer slot
#[test]
fn matrix_procedure_typed_variable_indirect_call() {
    assert_eq!(
        run_function("Mod/Tests/Matrix/M_ProcType_IndirectCall.cp", "Run"),
        49,
        "matrix probe procedure_typed_variable_indirect_call (procedure-typed variable invoked via name() syntax — indirect call through the function-pointer slot — §6.5 / 10) returned the wrong value",
    );
}

/// CP §10.2 — subclass override calls Super^ to chain into the base implementation
#[test]
fn matrix_super_call_lands_in_base_method_body() {
    assert_eq!(
        run_function("Mod/Tests/Matrix/M_SuperCall_SameModule.cp", "Run"),
        30,
        "matrix probe super_call_lands_in_base_method_body (subclass override calls Super^ to chain into the base implementation — §10.2) returned the wrong value",
    );
}

