DEFINITION MODULE Console;

PROCEDURE WriteInt*(x: INTEGER);
PROCEDURE WriteReal*(x: REAL);
PROCEDURE WriteChar*(x: CHAR);
PROCEDURE WriteString*(s: ARRAY OF CHAR);
PROCEDURE WriteShortString*(s: ARRAY OF SHORTCHAR);
PROCEDURE WriteLn*;
PROCEDURE ReadInt*(VAR x: INTEGER);
PROCEDURE ReadChar*(VAR x: CHAR);
PROCEDURE ReadString*(VAR s: ARRAY OF CHAR);

END Console.
